language: python
python:
 - "3.5"
 - "3.6"
 - "3.7"
install:
 - pip3 install -r requirements.txt coverage coveralls
 - python3 download_corpora.py
script:
  - coverage run --source scraper tests
after_success:
  coveralls
