FROM python:3.7-slim

RUN apt-get update && \
    apt-get -y install gcc git

RUN pip3 install --no-cache-dir flask uwsgi
COPY . .
RUN pip3 install -r requirements.txt

EXPOSE 8080
CMD ["uwsgi", "./wsgi.ini"]
